nix-community/ethereum.nix

- README.md
- flake.nix
- overlays.nix
- packages/clients/consensus/prysm/default.nix
- packages/clients/execution/geth/default.nix
This PR brings the following execution clients:
> feat: add geth, mev-boost and mev-geth

- checks.nix
- flake.nix
- lib/exportPackages.nix
This PR fixes a bad configuration on `checks.nix` for `nix-linter`.
> fix: solve bad configuration of nix-linter

- .envrc
For an overview of the benefits see [nix-direnv](https://github.com/nix-community/nix-direnv).
> feat: add nix-direnv

- modules/erigon.nix
Much like Geth, Erigon's interpretation of toml/yaml config is a bit non-standard and as a result generating the correct yaml from the nix config is non-trivial and error prone. 
This PR moves back to using args, which seems to be the least brittle approach with the best documentation.
> fix: move erigon back to args pattern

- packages/clients/execution/erigon/default.nix
Another erigon update from 2.35.2 to 2.36.1.
Also tried to update via `nix-update`: it took 9m47s, dunno why so long
> chore(erigon): update erigon 2.35.2 -> 2.36.1

- packages/signers/web3signer/default.nix
Update web3signer from [22.11.0 to 23.1.0](https://github.com/ConsenSys/web3signer/compare/22.11.0...23.1.0)
> chore(web3signer): update web3signer 22.11.0 -> 23.1.0

- packages/clients/execution/erigon/default.nix
New erigon version: [v2.37.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.37.0)
> chore(erigon): update erigon 2.36.1 -> 2.37.0

- packages/clients/execution/erigon/default.nix
Update erigon to latest version: [v2.38.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.38.0)
> chore(erigon): update erigon 2.37.0 -> 2.38.0

- flake.nix
This PR sets correctly `pkg` and `lib` for flake.parts by setting them on `imports` clause.
> fix: move pkgs and lib to imports

- packages/clients/execution/erigon/default.nix
Again a new erigon update to [v2.38.1](https://github.com/ledgerwatch/erigon/releases/tag/v2.38.1)
> chore(erigon): update erigon 2.38.0 -> 2.38.1

- packages/utils/ethdo/default.nix
Update ethdo to [1.28.0](https://github.com/wealdtech/ethdo/releases/tag/v1.28.0).
Should I also update bls/mcl libs? Do you have some policy about lib updates?
> chore(ethdo): update ethdo 1.25.3 -> 1.28.0

- packages/clients/execution/geth/default.nix
Update geth to [v1.11.0](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0)
> chore(geth): update geth 1.10.26 -> 1.11.0

- packages/clients/execution/geth/default.nix
Update geth to [v1.11.1](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.1)
> chore(geth): update geth v1.11.0 -> v1.11.1

- flake.nix
Removes unnecessary specification of `nixpkgs` in `flake.parts` (it's the default action inside the framework).
> chore: removal of unnecessary nixpkgs specification for flake.parts

- packages/clients/execution/erigon/default.nix
Update erigon to [v2.39.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.39.0)
> chore(erigon): update erigon 2.38.1 -> 2.39.0

- flake.lock
- packages/clients/consensus/lighthouse/default.nix
Update lighthouse to [v3.5.0](https://github.com/sigp/lighthouse/releases/tag/v3.5.0)
I also updated nixpkgs, because in current version `rustPlatform.buildRustPackage` use rustc version `1.66.1`, which can't compile this release. In last nixpkgs rustc version is `1.67.0` and it works fine.
From lighthouse discord:
> chore(lighthouse): update lighthouse v3.4.0 -> v3.5.0

- flake.lock
- flake.nix
- packages/default.nix
`nix fmt` was broken with a glibc error and I've been noticing issues with latest unstable across a few projects the last few days.
In general I think we should be building on the latest stable release and bringing in unstable only when necessary
> feat: prefer nixpkgs stable

- packages/clients/execution/geth/default.nix
Diff: https://github.com/ethereum/go-ethereum/compare/v1.11.2...v1.11.3
> geth: 1.11.2 -> 1.11.3

- packages/clients/execution/erigon/default.nix
Diff: https://github.com/ledgerwatch/erigon/compare/v2.39.0...v2.40.1
> erigon: 2.39.0 -> 2.40.1

- flake.lock
- flake.nix
I checked `hercules-ci` and found out that we have long-running tasks because we haven't `aarch64-darwin` and `x86_64-darwin` agents to build them. I check the docs and found that we can restrict the [systems](https://flake.parts/options/hercules-ci-effects.html#opt-herculesCI.ciSystems) which we want to use for packages/checks build.
Tried to do that and seems it [works](https://hercules-ci.com/github/nix-community/ethereum.nix/jobs/923).
> feat(ci-hercules): restrict ciSystems

- .github/workflows/gh-pages.yaml
- .github/workflows/update-inputs.yaml
- .github/workflows/update-packages.yaml
Add gpg signs to github actions when we want to update packages and lock.
Someone need to add `GPG_PRIVATE_KEY` and  `GPG_PASSPHRASE` secrets with verified (or nor, do we have a policy about that?) email.
The example of workflow execution: https://github.com/selfuryon/ethereum.nix/pull/11 and https://github.com/selfuryon/ethereum.nix/pull/12
> feat(workflows): add gpg-signs

- modules/backup/default.nix
- modules/restore/default.nix
When specifying the repository via `RESTIC_REPOSITORY_FILE` the variable `RESTIC_REPOSITORY` is not set.
The log message which required it was superfluous anyway.
> fix(modules/backup): remove reference to RESTIC_REPOSITORY in backup script

- flake.lock
- nix/shell.nix
Hello!
After update my system I found out that `mission-control` changed [the way how to work](https://github.com/Platonic-Systems/mission-control/pull/30/files) with devShell. Fix that before `Update Flake Inputs` task performs an update.
> chore(mission-control): replace installToDevShell with a new config option

- packages/default.nix
- packages/editors/vscode/extensions/ackee-blockchain.solidity-tools/default.nix
- packages/editors/vscode/extensions/consensys.vscode-solidity-auditor/default.nix
Adds support for some useful VSCode plugins:
- [Solidity Auditor](https://github.com/ConsenSys/vscode-solidity-auditor)
- [Tools for Solidity](https://github.com/Ackee-Blockchain/tools-for-solidity-vscode)
In the case of Tools for Solidity, also I'll include a new PR support for [woke](https://github.com/Ackee-Blockchain/woke).
> feat: add acktree-blockchain.solidity-tools and consensys.vscode-solidity-auditor plugins

- packages/clients/consensus/prysm/default.nix
* Prysm currently builds on go 1.19: https://github.com/prysmaticlabs/prysm/blob/08d6eccfb3bca915ff7d6369677b3f9ab9bacb55/.github/workflows/go.yml
* If using unstable or staging-next packages in Nix, you could end up with go 1.2x, which breaks Prysm due to this: https://github.com/trailofbits/go-mutexasserts/pull/2 (this fix is merged, but not yet in prysm)
> Fix prysm build when nix env is go 1.2x

- flake.nix
Repeat #221, still wait a signed commit there
Close #221
> fix: remove default cachix substituter from flake.nix

- .github/workflows/update-packages.yaml
- packages/default.nix
- packages/mev/mev-boost-builder/default.nix
Found that `build/ci.go` [downloads](https://github.com/flashbots/builder/blob/main/build/ci.go#L142) go v1.20.2 by default, so I switched to an unstable nixpkgs to use go 1.20 in builds
Close #223
> fix: switch to go 1.20 for mev-boost-builder building

- flake.nix
Migrated to `flake-parts.lib.mkFlake`, it's a default way to make flake, and it seems more clean for me.
> chore(flake-parts): move to flake-parts.lib.mkFlake

- modules/erigon/default.nix
Using websockets breaks because the module expects `ws.port` but doesn't define an arg for it... which is correct since Erigon doesn't have a `ws.port` flag.
> Fix erigon --ws

- README.md
- docs/getting-started/installation.md
- flake.lock
- flake.nix
- mkdocs.nix
- modules/testing.nix
- nix/checks.nix
- nix/default.nix
- nix/formatter.nix
- nix/shell.nix
This PR introduces [`devshell`](https://github.com/numtide/devshell) rather than using `mission-control`
> feat: introduction of devshell

- .gitignore
Just ignore `repl-result` when using `nix repl` and `:bl <derivation>` command.
> chore: ignore repl-results

- default.nix
- flake.lock
- flake.nix
- shell.nix
Migrates `flake-compat` to use `nix-community`'s supported version.
> feat: migrate flake-compat to use supported nix-community version

- packages/clients/consensus/lighthouse/default.nix
- packages/clients/consensus/prysm/default.nix
- packages/clients/consensus/teku/default.nix
- packages/clients/execution/besu/default.nix
- packages/clients/execution/erigon/default.nix
- packages/clients/execution/geth-sealer/default.nix
- packages/clients/execution/geth/default.nix
- packages/clients/execution/nethermind/default.nix
- packages/default.nix
- packages/dvt/charon/default.nix
- packages/dvt/ssvnode/default.nix
- packages/libs/bls/default.nix
- packages/libs/evmc/default.nix
- packages/libs/mcl/default.nix
- packages/mev/dreamboat/default.nix
- packages/mev/mev-boost-builder/default.nix
- packages/mev/mev-boost-prysm/default.nix
- packages/mev/mev-boost-relay/default.nix
- packages/mev/mev-boost/default.nix
- packages/mev/mev-rs/default.nix
- packages/signers/dirk/default.nix
- packages/signers/web3signer/default.nix
- packages/utils/eth2-testnet-genesis/default.nix
- packages/utils/ethdo/default.nix
- packages/utils/ethereal/default.nix
- packages/utils/sedge/default.nix
- packages/utils/staking-deposit-cli/default.nix
- packages/utils/zcli/default.nix
- packages/validators/vouch/default.nix
This PR brings two minor improvements:
- Use sri `hash` instead of `sha256`
- Addition of `meta.mainProgram` so, when using `lib.getExe` the correct or default main binary is selected.
> chore: use hash instead of sha256 and addition of mainPogram in metadata

- packages/clients/execution/erigon/default.nix
Diff: https://github.com/ledgerwatch/erigon/compare/v2.43.0...v2.43.1
> erigon: 2.43.0 -> 2.43.1

- packages/signers/web3signer/default.nix
Update web3signer to [v23.6.0](https://github.com/ConsenSys/web3signer/releases/tag/23.6.0)
> chore(web3signer): update web3signer to v23.6.0

- .github/workflows/update-packages.yaml
- packages/clients/execution/erigon/default.nix
Update erigon to [v2.46.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.46.0) and remove erigon from blacklist (they do normal semver tags again)
Close #264
> feat(erigon): update  to v2.46.0

- .github/workflows/update-packages.yaml
- packages/clients/execution/geth-sealer/default.nix
Update geth-sealer to [v1.12.0](https://github.com/manifoldfinance/geth-sealer/releases/tag/geth-sealer-v1.12.0) and remove it from blacklist (I updated it via `nix-update` successfully) 
Close #248
> chore(geth-sealer): update geth sealer

- packages/default.nix
- packages/libs/crytic-compile/default.nix
- packages/solidity/analyzers/slither/default.nix
We couldn't update `slither` because unstable nixpkgs has a `0.3.0` crytic-compile version, but the latest `slither` needs at least `0.3.3`. I added `crytic-compile` as a package dependency until nixpkgs will merge [this PR](https://github.com/NixOS/nixpkgs/pull/230067)
> feat(slither): update slither and add a crytic-compile as a lib

- packages/signers/web3signer/default.nix
Update web3signer to [23.8.1](https://github.com/Consensys/web3signer/releases/tag/23.8.1)
> chore: update web3signer

- packages/dvt/ssvnode/default.nix
[The last couple releases](https://github.com/bloxapp/ssv/releases) were for Jato V2, but this one looks like a mandatory for mainnet, so I updated the version.
Diff: https://github.com/bloxapp/ssv/compare/v0.5.4...v1.0.0-rc.1
> ssvnode: 0.5.4 -> 1.0.0-rc.1

- packages/signers/web3signer/default.nix
Update web3signer to [v23.9.0](https://github.com/Consensys/web3signer/releases/tag/23.9.0)
> chore(web3signer): update v23.8.1 -> v23.9.0

- .github/workflows/update-packages.yaml
Consider to disable auto update for these packages:
* mev-boost: until they will make a new release tag. Actually, it's very strange that `nix-update` try to update it to a pre-release version (1.6.0 -> 1.6.4844-dev2)
* erigon: until we fix its build #370 [Done]
* nethermind: until we fix build with Package Source Mapping #345
> chore(workflows/update-packages): blacklist some packages

- modules/erigon/args.nix
- modules/geth/args.nix
- modules/prysm-beacon/args.nix
- modules/prysm-validator/args.nix
Add `holesky` testnet to enum types for Prysm/Geth/Erigon. 
MEV-Boost is left untouched (no upstream support yet)
> chore: Add "holesky" testnet to enums

- packages/clients/consensus/prysm/default.nix
- packages/libs/bls/default.nix
- packages/libs/blst/builder.sh
Hello!
I tried to compile a prysm version [v4.1.0-alpha.0](https://github.com/prysmaticlabs/prysm/releases/tag/v4.1.0-alpha.0), because only this version supports holesky, and I faced with issue in blst integration: 
```
cgo_assembly.S:1:10: fatal error: assembly.S: No such file or directory
1 | #include "assembly.S"
|          ^~~~~~~~~~~~
compilation terminated.
```
So I added `assembly.S` to output for blst and after that prysm build works fine.
In additional, I bumped a bls version + add a version setting for prysm during the build.
> chore: bump bls version + add assembly.S to $out/include for blst

- packages/clients/consensus/prysm/default.nix
- packages/clients/execution/geth/default.nix
- packages/libs/bls/default.nix
- packages/libs/blst/default.nix
- packages/libs/crytic-compile/default.nix
- packages/libs/evmc/default.nix
- packages/libs/mcl/default.nix
for https://github.com/nix-community/ethereum.nix/issues/284
Seems libs i patched are old, devs improved arm build in master. may be should update.
```
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ nix build .#prysm -L --show-trace
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ uname -a
Linux Ubuntu-2204-jammy-arm64-base 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:34:05 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
actions-runner@Ubuntu-2204-jammy-arm64-base:~/github.com/nix-community/ethereum.nix$ 
```
> feat(prysm): arm support

- docs/getting-started/running-lighthouse-beacon.md
- mkdocs.yml
- modules/default.nix
- modules/lighthouse-beacon/args.nix
- modules/lighthouse-beacon/default.nix
- modules/lighthouse-beacon/options.nix
- modules/lighthouse-validator/args.nix
- modules/lighthouse-validator/default.nix
- modules/lighthouse-validator/options.nix
Implement services for Lighthouse Beacon Node and Validator Client.
I feel like the only particularly controversial thing in this PR is making the network default to the name of the beacon/validator service.
Resolves #20
> feat: Implement lighthouse beacon service

- packages/clients/consensus/prysm/default.nix
Prysm has dependencies which prevent it from being built with Go 1.21 (now default on unstable), so we have to pin it to Go 1.20.
Error message:
```
> vendor/github.com/quic-go/quic-go/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```
> prysm: build with go 1.20

- packages/default.nix
- packages/utils/eigenlayer-cli/default.nix
EigenLayer has a [cli utility](https://github.com/NethermindEth/eigenlayer/tree/develop) to manage operator settings. I think it would be helpful to have it here
> feat(eigenlayer-cli): add eigenlayer-cli

- flake.lock
- flake.nix
- mkdocs.nix
- packages/clients/consensus/lodestar/default.nix
- packages/default.nix
- packages/solidity/frameworks/wake/default.nix
We have been using `devour-flake` to build all inputs but recently when we switched to `buildbot` it skipped building it as it's only a `shellApplication` that needs to be run. This restores what we used to have for building all packages inside the check.
> fix: revert to build packages manually in flake check

- docs/apps.md
- packages/clients/execution/reth/default.nix
- packages/default.nix
Add `reth` EL client.
Close #323
> feat(reth): add reth execution client

- packages/utils/tx-fuzz/default.nix
vendorSha256 is obsolete and throws a warning.
> Move tx-fuzz from vendorSha256 to vendorHash.

- packages/clients/execution/besu/default.nix
Besu had a global outage at block 18947893. This fixes the issue.
> besu: 23.10.1 -> 23.10.3-hotfix

- packages/clients/consensus/nimbus/default.nix
- packages/default.nix
This commit make the nimbus package build the stand-alone validator client by default. The stand-alone validator is documented here: https://nimbus.guide/validator-client.html.
> nimbus: Also build nimbus_validator_client

- flake.lock
- flake.nix
- packages/clients/consensus/lighthouse/default.nix
- packages/default.nix
- packages/dvt/ssvnode/default.nix
- packages/solidity/frameworks/wake/default.nix
I did:
* update wake to the latest version
* switch to the latest stable nixpkgs version (poetry2nix doesn't work with `23.05` https://github.com/nix-community/poetry2nix/issues/1422)
I also need to instantiate `poetry2nix.mkPoetryApplication`, but I can't. I hope it close #421
> chore: update wake and switch to nixpkgs 23.11

- packages/clients/execution/erigon/default.nix
Also disable sandworm explicitly, as libsandworm_capi.so requires libgmp, which the Go linker fails to find.
> erigon: 2.54.0 -> 2.57.0

- packages/clients/consensus/prysm/default.nix
https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.0
> prysm: 4.1.0 -> 4.2.0

- flake.lock
- flake.nix
Avoid duplicate inputs in the flake.lock.
As a consumer of the flake, it makes it easier to pass my own version
of flake-utils, systems, ...
> flake: compress dependency tree

- packages/solidity/frameworks/wake/default.nix
poetry2nix reads the pyproject.toml. but that creates an IFD. by moving
the fetch to eval time, we avoid that issue.
> fix: restore flake show

- flake.nix
- packages/default.nix
Create the default overlay manually as https://github.com/NixOS/nixpkgs/pull/269551 seems to have caused some issues with easyOverlay where it's trying to touch an i686 package when that system is not in the listed systems.
> fix: remove easyOverlay

- packages/default.nix
- packages/utils/rocketpool/default.nix
Adds the Rocket Pool CLI to the utils packages.
Regarding the overlayAttrs: when I tried to use the overlay in my nixos config, it didn't work. I had to list out the packages to make it work. I am not sure why this is the case. If someone can tell me if this is known to work, I'd like to see what the `nixpkgs.overlays` looks like to make it work.
> feat(rocketpool): Add the Rocket Pool CLI

- packages/default.nix
- packages/utils/heimdall/default.nix
A handy toolkit for EVM bytecode analysis.
Confirmed working on `x86_64-linux`, ~it *should* work on darwin but haven't tested.~
---
Edit: OK just tested locally on `aarch64-darwin` too and added a commit to add some missing deps - should be good to go :ok_hand:
> heimdall: init at 0.7.3

- packages/clients/execution/reth/default.nix
- packages/default.nix
Also removes some redundant deps and switches to `callPackageUnstable` as the latest `reth` requires rust `1.75`.
> reth: 0.1.0-alpha.13 -> 0.1.0-alpha.16

- modules/erigon/args.nix
- modules/erigon/default.nix
- modules/geth/args.nix
- modules/geth/default.nix
- modules/nethermind/args.nix
- modules/nethermind/default.nix
This MR adds an optional`datadir` argument to the nethermind, geth, and erigon modules to better match other module behavior (lighthouse, prysm).
> feat: Allow configurable erigon, geth, nethermind datadir

- docs/nixos/running-nimbus-beacon.md
- mkdocs.yml
- modules/default.nix
- modules/nimbus-beacon/args.nix
- modules/nimbus-beacon/default.nix
- modules/nimbus-beacon/options.nix
Implements Nimbus Beacon service (validator service to follow).
Two things I think could be contentious:
* Using `ExecPreStart` for the checkpoint sync. Nimbus has this implemented somewhat awkwardly IMO, in that it's a separate command. `ExecPreStart` has a timeout of 15 mins; in all my testing the checkpoint finished downloading in 2 or 3 mins, but had it not completed before the timeout, the systemd service will fail to start. We can as well adjust that 15 minute timeout to be longer or infinite.
* Opening REST and Metrics ports by default. This seems to be done by default in Lighthouse at least, which i used for reference for a lot of this, however I would argue that the majority of users would not want these exposed and as such maybe it should be a more explicit enable, either within …
> feat: implement Nimbus beacon service

- modules/nimbus-beacon/default.nix
If `rest.enable` is true and `rest.allow-origin` is not set, `allow-origin` defaults to null which can't be coerced to a string when building CLI flags for Nimbus. This MR fixes this behavior by adding a null check before building the flag.
> fix: nimbus-beacon rest.allow-origin bad default

- .github/workflows/update-packages.yaml
- packages/default.nix
- packages/dev/foundry/default.nix
- packages/dev/foundry/svm-lists/linux-amd64.json
- packages/dev/foundry/svm-lists/macosx-amd64.json
- packages/dev/foundry/update-svm-lists.sh
This introduces a new built-from-source `foundry` package and renames the old binary package from the `foundry.nix` repo to `foundry-bin` following the `nixpkgs` convention.
One quirk of `foundry` builds is the `svm-rs` crate dependency, which by default fetches a list of all available `solc` binaries for each platform`build.rs`. As there is no hash or versioning of the file itself, the file can change between fetches (e.g. when new solc versions are added).
Fortunately svm-rs exposes a `SVM_RELEASES_LIST_JSON` env var which allows for pointing to a local file path instead making support for Nix feasible without having the package break each time a new `solc` version is released. A script called `update-svm-lists.sh` is included that allows for downloading the latest lists for linux and …
> foundry: init at nightly-0688b5a

- .github/workflows/update-packages.yaml
add foundry, lighthouse, wake and reth to blacklist for updating. After this change update script is working: https://github.com/nix-community/ethereum.nix/pull/466
P.S.: I'm thinking about rewriting the update script to work like in nixpkgs, where the update script runs `passthru.updateScript` instead of a hardcoded updater. I tried to use nixpkgs `update.nix` (got the idea from [here](https://discourse.nixos.org/t/how-can-i-run-the-updatescript-of-personal-packages/25274/3)) but I'm still struggling to make it work
> chore: add foundry, lighthouse, wake and reth to blacklist for updating

- pkgs/default.nix
- pkgs/vouch/unstable.nix
This is needed mostly during hard forks where unstable software is
needed to test things on test networks like Holesky.
> add vouch-unstable

- pkgs/blutgang/default.nix
- pkgs/default.nix
Consider adding blutgang, a load balancer for Ethereum RPC calls into the repository.
The canary pre-release supports WS RPC in addition to HTTP RPC, for which the initial proposition is to add this pre-release package.
> blutgang: init at 0.3.0-canary2

- pkgs/blutgang/default.nix
- pkgs/default.nix
Includes fixes up to this comment on this tracking ticket: https://github.com/rainshowerLabs/blutgang/issues/57#issuecomment-1961721149
A more recent Rust version is also needed for the project to now compile.
> blutgang: 0.3.0-canary2 -> 0.3.1

- pkgs/prysm/default.nix
Diff: https://github.com/prysmaticlabs/prysm/compare/v4.2.1...v5.0.0
> prysm: 4.2.1 -> 5.0.0

- pkgs/nimbus/default.nix
Builds with `nix build '.#nimbus'`. From the release announcement: "This is a hotfix release addressing a consensus violation issue affecting Deneb-transitioned network such as Holešky. Please upgrade as soon as possible if your node is affected."
> nimbus: 24.2.1 -> 24.2.2

- pkgs/mev-boost/default.nix
Dencun update, tested that binary starts.
On the [release page](https://github.com/flashbots/mev-boost/releases/tag/v1.7), the authors recommend Go `1.22`. However, that is not package on Nix yet. Despite the recommendation, the program seems to compile and start fine.
> mev-boost: 1.6.0 -> 1.7

- pkgs/geth/default.nix
Diff: https://github.com/ethereum/go-ethereum/compare/v1.13.12...v1.13.14
> geth: 1.13.12 -> 1.13.14

- pkgs/default.nix
- pkgs/rotki-bin/default.nix
I had a quick go at building it from source following [the guide][1], then decided on just wrapping the appimage after running into some python build issues related to the `ruff` linter that was being invoked in a build phase for some reason. I'm sure it's doable with some patching if someone's keen enough, but this at least makes the package available for now.
[1]: https://rotki.readthedocs.io/en/latest/installation_guide.html#build-from-source
> rotki-bin: init at 1.32.1

- pkgs/reth/default.nix
Marks the first beta release of `reth`. 
Updated with [nix-update](https://github.com/Mic92/nix-update), tested that it builds and prints the help command on x86-linux.
> reth: 0.1.0-alpha.21 -> 0.2.0-beta.1

- pkgs/default.nix
- pkgs/eth-validator-watcher/default.nix
Kilnfi's validator watcher.  May be interesting to anyone who wants to roll their own notifier, for upcoming block proposals etc. rather than relying on an external service such as beaconcha.in
I have tried this with lighthouse and it works (using the generic beacon API)
> eth-validator-watcher: init at 0.7.1

- pkgs/prysm/default.nix
* https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.2
* https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.1
> prysm: 5.0.0 -> 5.0.2

- pkgs/rocketpool/default.nix
`nix flake check` is having issues due to other packages (https://github.com/nix-community/ethereum.nix/pull/497#issuecomment-1994983204), but the rocketpool package is building fine for me.
> rocketpool: 1.11.7 -> 1.12.1

- pkgs/geth/default.nix
This PR closely resembles the nixpkgs's [one](https://github.com/NixOS/nixpkgs/pull/311188). I did have the very same error for `#include "os/events_posix.h"`.
I'm very much in favor of https://github.com/nix-community/ethereum.nix/issues/296.
> geth: 1.13.14 -> 1.14.3

- pkgs/reth/default.nix
I don't have `x86_64-darwin` machine, so didn't test it. I can remove it from platforms, though.
Also, reth-0.2.0-beta.1 seems to be changed, as I can't reproduce cached build.
> Update reth and support `x86_64-darwin`

- pkgs/nimbus/default.nix
`nix build '.#nimbus'` works for me. Also the validator binary does its job, which is the only binary I am using from this package.
> nimbus: 24.3.0 -> 24.5.1

- pkgs/erigon/default.nix
`nix build .#erigon` works and an old node of mine is making progress on the sync.
> erigon: 2.58.1 -> 2.60.0

- README.md
- docs/index.md
Hello there 👋!
The NixOS wiki is in the process of migrating from https://nixos.wiki to https://wiki.nixos.org.
You can find more information about it [here](https://github.com/NixOS/foundation/issues/113).
You seem to be using the old link in your repository, which is why we send you this PR.
If you feel like this is not correct or have any questions, feel free to [get in touch with us](https://github.com/NixOS/nixos-wiki-infra/issues/105).
Have a great day,
-- The NixOS Wiki-Team ❄️
> Update NixOS Wiki link

- pkgs/geth/default.nix
I do have another vendorHash than [nixpkgs](https://github.com/NixOS/nixpkgs/pull/326432) but I have been running this in prod for a couple of days just fine.
> geth: 1.14.3 -> 1.14.7

- modules/default.nix
- modules/reth/args.nix
- modules/reth/default.nix
- modules/reth/options.nix
I tested this against Reth 1.0 (from #530), however I don't think the command line has changed since the current imported version (0.2.0-beta.6) so I opted to implement it against `main` instead of on top of my other PR.
I chose not to implement and integration test with a nixos vm because I felt it is mostly likely unecessary due to the extensive test coverage within Reth itself.
> Implement Reth service module

- pkgs/default.nix
- pkgs/rocketpoold/default.nix
Need the daemon to write a rocketpool module that works without docker.
Perhaps it could be included in the rocketpool (client) package? But the build environment conflicts and I'm not sure how best to overcome that, other than just package it separately.
> rocketpoold: init at 1.13.7

- modules/nethermind/default.nix
Module was missing a backslash and included a systemd option that causes a core dump, presumably because it isn't compatible with JIT elements in the dotnet runtime
> Fix nethermind module

- pkgs/lighthouse/Cargo.lock
- pkgs/lighthouse/default.nix
Biggest change for this update are:
-  remove `alloy-consensus-0.1.0`
- add `quick-protobuf-0.8.1`
- update hash of `libmdbx-0.1.4`
in `cargoLock.outputHashes` attribute set.
> lighthouse: 5.2.1 -> 5.3.0

- pkgs/geth/default.nix
The biggest change is that the p2psim package got dropped: https://github.com/ethereum/go-ethereum/pull/30250
> geth: 1.14.7 -> 1.14.8

- modules/nimbus-beacon/args.nix
- modules/nimbus-beacon/default.nix
Fixes the nimbus module failing because of the MemoryDenyWrite security option. 
Also adds options to enable the keymanager API.
> Fix memorydenywrite issue and add keymanager API

- pkgs/mev-boost/default.nix
It builds and runs. I've not yet tested it live but it's identical to the package in nixpkgs which was updated a month ago.
> mev-boost: 1.7 -> 1.8

- pkgs/erigon/default.nix
Note that erigon's version tags are no longer prefixed with a `v` (starting from [2.60.7](https://github.com/erigontech/erigon/releases/tag/2.60.7))
> erigon: 2.60.0 -> 2.60.8

- pkgs/vouch/default.nix
There was a small issue with the 1.9.0 release:
https://github.com/attestantio/vouch/releases/tag/v1.9.2
> vouch: 1.9.0 -> 1.9.2

- pkgs/default.nix
- pkgs/ssvnode/default.nix
Draft until the real v2 is released. This updates upgrades the Go version. The current branch uses weird openssl loading feature, for which a postFixup had to be added (alternatively, a runtime environment could set `LD_LIBRARY_PATH`). If anyone has a better idea how to work around this, please do comment.
> ssvnode: 1.3.8 -> 2.0.0

- modules/mev-boost/args.nix
- modules/mev-boost/default.nix
- modules/mev-boost/default.test.nix
Contains the following changes:
- Remove goerli as it is retired and no longer a valid network option.
- Fix the cli option generation so that it works with the change in mev-boost v1.8 to use the urfave cli library.
Resolves issue #558 
The mev-boost test passes for me now.
> fix mev-boost module option generation and network options

- flake.lock
- flake.nix
- pkgs/blutgang/default.nix
- pkgs/foundry/default.nix
- pkgs/foundry/svm-lists/linux-amd64.json
- pkgs/foundry/svm-lists/macosx-amd64.json
- pkgs/nethermind/default.nix
- pkgs/nethermind/nuget-deps.nix
- pkgs/nimbus/default.nix
- pkgs/nimbus/fix-hash.patch
- pkgs/reth/default.nix
the plan is to do `nix flake update --commit-lock-file` and then get green on buildbot. Incorporates #560 #561 and #562. As discussed in #560 we drop support for reth on Darwin. I haven't touched the `nixos-24.05` input but this should be done asap
> Update flake dependencies

- modules/nimbus-beacon/args.nix
- modules/nimbus-beacon/default.nix
- pkgs/nimbus/default.nix
depends on #568
Nimbus needs to be recompiled for Gnosis Chain and Chiado. This is neatly handled by upstream Makefile, we just need to enable it and pick the right binary at configuration time. Currently running on my machine with seemingly no issues.
> feat: Nimbus on Gnosis chains

- pkgs/geth/default.nix
> This is a security release, fixing a vulnerability (https://github.com/advisories/GHSA-q26p-9cq4-7fc2).
>
> Please update your nodes ASAP.
https://github.com/ethereum/go-ethereum/releases/tag/v1.14.13
> geth: 1.14.8 -> 1.14.13

- pkgs/default.nix
- pkgs/rotki-bin/default.nix
switched from `callPackage2311` to `callPackageUnstable` because 23.11 is EOL and `wrapProgram` didn't work on regular `callPackage`, idk why, it works on `callPackageUnstable`.
the rest of pr should be self-explanatory
> rotki-bin: 1.33.1 -> 1.37.1; add icon and enable wayland

- modules/lighthouse-validator/default.nix
the condition is backwards. As a result:
- If you set the option to `[]`, it fails at runtime with `error: a value is required for '--beacon-nodes <NETWORK_ADDRESSES>' but none was supplied`.
- if you set is to `[my-beacon-enpoint]`, it uses the default value (or lighthouse-beacon value) instead.
> fix lighthouse args.beacon-nodes

- pkgs/foundry/default.nix
https://www.paradigm.xyz/2025/02/announcing-foundry-v1-0
It seems sensible that the default derivation should be stable at this point. There's also [foundry.nix](https://github.com/shazow/foundry.nix) for nightlies
> foundry: nightly -> 1.0.0

- pkgs/reth/default.nix
This release supports the Pectra fork for Holesky and Sepolia: https://github.com/paradigmxyz/reth/releases/tag/v1.2.0
> reth: 1.1.5 -> 1.2.0

- modules/nethermind/args.nix
- modules/nethermind/default.nix
Separate the RPC host and engine host options so that they can, for example, bind to different interfaces
> Separate nethermind JSON RPC Host and EngineHost options

- pkgs/default.nix
seems to have been mistakenly commented out in #588
> fix: nimbus

- pkgs/by-name/re/reth/default.nix
`reth` has supported building for ARM platforms since [at least 1.1.4](https://github.com/paradigmxyz/reth/releases/tag/v1.1.4), which precedes the current version we have pinned (1.2.0).
> feat: Enable `aarch64-darwin`, `aarch64-linux` support for `reth`

- pkgs/by-name/fo/foundry/default.nix
- pkgs/by-name/fo/foundry/svm-lists/linux-amd64.json
- pkgs/by-name/fo/foundry/svm-lists/macosx-amd64.json
Originally this was disabled as solc were not providing builds for `aarch64-darwin`, however since version 0.8.24 they have switched to building "universal" binaries for macos. See this issue for context:
- https://github.com/ethereum/solidity/issues/12291
Unfortunately there are no ARM builds for linux just yet, so we still need to manually specify the supported architectures rather than using `platforms.unix`.
Ideally we'd have our own derivations for all the solc versions and just build them for every platform we want to support ourselves, but this likely wouldn't play nicely with tools like foundry that implicitly try to download the static binaries when the user tries to run forge commands.
This PR also runs the `update-svm-lists.sh` script to enable support for solc `0.8.29`.
> feat: Enable `aarch64-darwin` support for `foundry`

- pkgs/by-name/we/web3signer/default.nix
This is a required upgrade for Electra (April 30th on Gnosis Chain and May 7th on Ethereum Mainnet)
https://github.com/Consensys/web3signer/releases/tag/25.4.1
> web3signer: 24.2.0 -> 25.4.1

- pkgs/by-name/ge/geth/default.nix
- pkgs/default.nix
This is the minimum version required for Pectra (May 7th on Ethereum)
https://github.com/ethereum/go-ethereum/releases/tag/v1.15.9
> geth: 1.14.13 -> 1.15.9

- pkgs/by-name/me/mev-boost/default.nix
- pkgs/default.nix
mev-boost 1.9
Needed to update nixpkgsUnstable to get a more recent version of Go.
> mev-boost: 1.8 -> 1.9

- flake.lock
- flake.nix
- pkgs/by-name/er/erigon/default.nix
- pkgs/default.nix
Not sure why we didn't already have a 24.11 nixpkgs input, we have old stable ones and unstable. I added the latest stable version and, in the future, I think a lot of packages could migrate to using the same nixpkgs 24.11 stuff that erigon needed & maybe we can remove some of the older nixpkgs. But that's not the focus of this PR.
The [erigon blog](https://erigon.tech/releasing-erigon-v3-0-0/) says this upgrade is required for Pectra. But beware: requires a complete resync if upgrading from the 2.x.x series
> erigon: 2.61.3 -> 3.0.3

- pkgs/by-name/pr/prysm/default.nix
https://github.com/prysmaticlabs/prysm/releases/tag/v5.3.1
This release is updated to Go 1.24 so bumped to use buildGo124Module.
> prysm: 5.3.0 -> 5.3.2

- pkgs/by-name/ge/geth/default.nix
Bumping geth to get some of the fixes and performance improvements after pectra release.
> Update geth to version 1.15.11.

- pkgs/by-name/et/ethstaker-deposit-cli/default.nix
- pkgs/default.nix
Has support for Hoodi testnet and a few other features that the official tool is lacking.
> ethstaker-deposit-cli: Init at 1.2.2

- pkgs/by-name/ge/geth/default.nix
bump version of go-ethereum ( https://github.com/ethereum/go-ethereum/releases/tag/v1.16.2 )
> geth: 1.16.1 -> 1.16.2

- pkgs/by-name/ethstaker-deposit-cli/default.nix
There are a new url here which we should I believe: https://github.com/ethstaker/ethstaker-deposit-cli
> chore(ethstaker-deposit-cli): change repo url
