nix-community/ethereum.nix

overlays.nix, packages/clients/execution/geth/default.nix
=> feat: add support to plugeth

README.md, overlays.nix, packages/libs/evmc/001-Disable-vmtester.patch, packages/libs/evmc/002-Disable-hunter-package.patch, packages/libs/evmc/default.nix
=> feat: add evmc lib

README.md
Removal of TO-DO section in the README.
=> chore: removal of TO-DO section

flake.nix, overlays.nix, packages/clients/execution/geth/default.nix, packages/clients/execution/mev-boost/default.nix, packages/clients/execution/mev-geth/default.nix, packages/clients/execution/plugeth/default.nix
This PR includes two improvements:
- Better code organization for `geth` forks.
- Updates relevant `geth` forks to latest stable version.
=> feat: better organization for geth's forks

packages/clients/consensus/lighthouse/default.nix, packages/clients/consensus/prysm/default.nix, packages/clients/consensus/teku/default.nix, packages/clients/execution/erigon/default.nix, packages/clients/execution/mev-boost/default.nix
This PR updates several versions of packages.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
=> feat: bump versions

README.md, flake.nix
Also removed keystores app for prysm which doesn't exist
=> feat: place prysm related packages under a prysm prefix

packages/clients/consensus/teku/default.nix
=> chore(teku): 22.11.0 -> 22.12.0

.gitignore, packages/clients/execution/geth/default.nix
=> chore(geth): 1.10.25 -> 1.10.26

packages/clients/execution/erigon/default.nix
=> chore(erigon): 2022.10.01 -> 2.30.0

README.md, overlays.nix, packages/signers/web3signer/default.nix
=> feat: add support for web3signer

packages/clients/execution/erigon/default.nix
=> chore(erigon): 2.30.0 -> 2.32.0

packages/clients/consensus/prysm/default.nix
=> chore(prysm): 3.1.2 -> 3.2.0

modules/geth.nix, modules/prysm/beacon.nix
=> chore: lint

checks.nix
it's currently broken and we are looking to replace it with statix anyway
=> fix: disable nix-linter

modules/default.nix, modules/erigon.nix, modules/geth.nix, modules/lib.nix, modules/prysm/beacon.nix
- feat(modules/geth): open firewall ports
- feat(modules): refactor and improve service script building
- feat(modules): add module for erigon
- feat(modules/geth): firewall improvements
- feat(modules/prysm-beacon): hardening improvements
=> feat: add erigon service and refine service implementations

flake.lock, flake.nix, nix/shell.nix
Add nix-update to make bumping packages easier.
=> feat: add nix-update

README.md, packages/default.nix, packages/signers/dirk/default.nix, packages/validators/vouch/default.nix
=> feat: add vouch and dirk

packages/default.nix, packages/mev/mev-rs/default.nix
=> feat: add mev-rs

packages/clients/execution/nethermind/default.nix
Diff: https://github.com/NethermindEth/nethermind.git/compare/1.16.0...1.16.1
=> nethermind: 1.16.0 -> 1.16.1

flake.lock, modules/clients/execution/default.nix, modules/clients/execution/nethermind.nix, modules/lib.nix, nix/checks.nix, packages/clients/execution/nethermind/default.nix, tests/default.nix, tests/nethermind.nix
=> feat: addition of nethermind service

modules/lib.nix
Boolean flags were not being properly generated.
=> fix(modules/lib): bad generation of boolean args

.github/workflows/update-nix-flakes.yaml
This PR introduces Github Actions to update each Sunday our nix flake inputs automatically.
=> feat: add update nix flake workflow

packages/clients/execution/besu/default.nix, packages/default.nix
Backport version of besu. Closes #102
=> feat(besu): add besu as a package

packages/clients/consensus/lighthouse/default.nix, packages/signers/web3signer/default.nix
Update web3signer to [23.2.0](https://github.com/ConsenSys/web3signer/releases/tag/23.2.0)
=> chore(web3signer): update web3signer 23.1.0 -> 23.2.0

packages/clients/consensus/teku/default.nix
Update teku to [v23.2.0](https://github.com/ConsenSys/teku/releases/tag/23.2.0)
=> chore(teku): update teku 23.1.1 -> 23.2.0

packages/clients/execution/besu/default.nix
Update besu to [v23.1.0](https://github.com/hyperledger/besu/releases/tag/23.1.0)
=> chore(besu): update besu 22.10.3 -> 23.1.0

packages/default.nix, packages/dvt/ssvnode/default.nix
=> feat: add support for ssvnode

flake.lock, flake.nix, packages/default.nix
This is a temporary solution until Foundry produces a stable release (as discussed in #126 with @shazow)
Closes #126
=> feat: add support to foundry

.envrc, flake.lock, flake.nix, nix/checks.nix, nix/shell.nix
=> chore: move to nix-update and statix from nixpkgs-unstable

.github/workflows/update-nix-flakes.yaml
changes:
* make pr-title and commits in conventional style
* fix pr number in output
=> chore: small improvements for workflows

packages/default.nix, packages/dvt/charon/default.nix
=> feat: add support to charon

packages/clients/execution/plugeth/default.nix
Diff: https://github.com/openrelayxyz/plugeth/compare/v1.10.25.0.0...v1.11.3.0.1
Update it manually due to https://github.com/nix-community/ethereum.nix/pull/163#discussion_r1134308823
=> chore(plugeth): update plugeth 1.10.25.0.0 -> 1.11.3.0.1

.github/workflows/update-inputs.yaml, .github/workflows/update-packages.yaml
=> chore(workflows): add gpg-fingerprint

modules/erigon/default.nix
=> fix: closes #187

packages/default.nix, packages/mev/mev-boost-relay/default.nix
Introduction of [mev-boost-relay](https://github.com/flashbots/mev-boost-relay).
=> feat: introduction of mev-boost-relay

packages/default.nix, packages/mev/mev-boost-builder/default.nix
Addition of [mev-boost-builder](https://github.com/flashbots/builder)
=> feat: mev-boost-builder

.github/workflows/update-packages.yaml, packages/default.nix, packages/mev/mev-boost-prysm/default.nix
This PR adds support for [flashbots forked `prysm` client](https://github.com/flashbots/prysm).
=> feat: mev-boost-prysm

README.md, mkdocs.nix, options-doc.nix
- chore(docs): remove redundant code
- feat(docs): improve docs generation
=> feat(docs): improve mkdocs

packages/default.nix, packages/mev/dreamboat/default.nix
It's a [mev-relay app](https://github.com/blocknative/dreamboat) from blocknative
=> feat(dreamboat): add a nev mev-relay app called dreamboat

packages/clients/consensus/lighthouse/default.nix
Update lighthouse to latest patch fix release [v4.0.2-rc.0](https://github.com/sigp/lighthouse/releases/tag/v4.0.2-rc.0)
=> chore(lighthouse): update lighthouse v4.0.1 -> v4.0.2-rc.0

.github/workflows/update-packages.yaml
I also changed the time this task starts to separate updating packages and inputs in time.
Close #218
=> chore(github-actions): remove lighthouse from auto-updates

packages/default.nix, packages/utils/ethereal/default.nix
=> feat: support for ethereal

.github/workflows/update-packages.yaml
=> chore: update packages daily

.github/workflows/update-packages.yaml, packages/default.nix, packages/utils/sedge/default.nix
Fixed sedge build, now it works
Close #201
=> fix: sedge build

packages/clients/consensus/teku/default.nix
Update teku to [23.4.0](https://github.com/ConsenSys/teku/releases/tag/23.4.0)
=> chore(teku): update teku 23.3.0 -> 23.4.0

packages/clients/execution/besu/default.nix
Update besu to [23.1.3](https://github.com/hyperledger/besu/releases/tag/23.1.3)
=> chore(besu): update besu 23.1.1 -> 23.1.3

.github/workflows/update-packages.yaml
The atom feed is returning a strange version.
=> fix(workflow): remove erigon from auto update

packages/default.nix, packages/utils/staking-deposit-cli/default.nix
=> feat: introduce staking-deposit-cli

modules/backup/default.nix, modules/erigon/default.nix, modules/geth-bootnode/default.nix, modules/geth/default.nix, modules/lib.nix, modules/nethermind/default.nix, modules/prysm-beacon/default.nix, modules/restore/default.nix
Minor PR that simplifies importing lib from modules
=> chore: simplify inputs for modules' lib

README.md
Improves what the Readme says.
=> feat: improvements to README

modules/default.nix, modules/prysm-beacon/args.nix, modules/prysm-beacon/default.nix, modules/prysm-validator/args.nix, modules/prysm-validator/default.nix, modules/prysm-validator/default.test.nix, modules/prysm-validator/options.nix, modules/testing.nix
=> Add service for Prysm validator

packages/clients/consensus/lighthouse/default.nix, packages/default.nix
Enable some tests for lighthouse
=> fix(lighthouse): enable tests

packages/clients/consensus/nimbus/default.nix, packages/default.nix
Added a `nimbus` package.
Close #7
=> feat: add nimbus

docs/index.md
=> chore: fix typo

mkdocs.nix
Fixes incorrect nixos module generation
=> fix: incorrect nixos module options generation

.github/mergify.yml, .github/workflows/gh-pages.yaml, .github/workflows/update-inputs.yaml, .github/workflows/update-packages.yaml
=> feat: introduction of mergify

docs/apps.md, packages/default.nix, packages/solidity/frameworks/wake/default.nix
=> woke: init at v3.2.6

docs/apps.md, packages/default.nix, packages/utils/tx-fuzz/default.nix
=> tx-fuzz: init at 1.3.2

flake.lock, flake.nix
=> chore: flake update

packages/clients/consensus/nimbus/default.nix
=> nimbus: 23.11.0 -> 24.1.2

packages/utils/rocketpool/default.nix
Update Rocketpool to the latest version.
=> update rocketpool 1.11.6 -> 1.11.7

packages/clients/consensus/nimbus/default.nix
Builds with `nix run '.#nimbus`.
=> nimbus: 24.1.2 -> 24.2.0

packages/utils/ethdo/default.nix
Generated with `nix-update -F ethdo`
=> ethdo: 1.33.2 -> 1.35.2

pkgs/reth/default.nix
bump Reth
verified with `nix run .#reth -- --version`
=> reth: v0.1.0-alpha.16 -> v0.1.0-alpha.17

pkgs/besu/default.nix
Builds with nix build '.#besu'
=> besu: 24.1.1 -> 24.1.2

pkgs/reth/default.nix
verified with `nix run .#reth -- --version`
=> reth: v0.1.0-alpha.17 -> v0.1.0-alpha.18

flake.nix
- feat: re-enable deno
- feat: configure mdformat with new withPlugins clause
=> feat: introduce deno formatter again

pkgs/reth/default.nix
verified with nix run .#reth -- --version
=> v0.1.0-alpha.18 -> v0.1.0-alpha.21 

pkgs/vouch/default.nix
=> vouch 1.8.0

pkgs/nethermind/default.nix, pkgs/nethermind/nuget-deps.nix
Diff: https://github.com/NethermindEth/nethermind/compare/1.25.3...1.25.4
=> nethermind: 1.25.3 -> 1.25.4

pkgs/ssvnode/default.nix
Diff: https://github.com/bloxapp/ssv/compare/v1.3.0...v1.3.1
=> ssvnode: 1.3.0 -> 1.3.1

pkgs/default.nix, pkgs/lighthouse/Cargo.lock, pkgs/lighthouse/default.nix, pkgs/lighthouse/use-c-kzg-from-crates-io.patch
Diff: https://github.com/sigp/lighthouse/compare/v4.6.0...v5.0.0
=> lighthouse: 4.6.0 -> 5.0.0

pkgs/lighthouse/Cargo.lock, pkgs/lighthouse/default.nix
https://github.com/sigp/lighthouse/releases/tag/v5.1.0
=> lighthouse: 5.0.0 -> 5.1.0

pkgs/vouch/default.nix
=> vouch 1.8.1

pkgs/lighthouse/Cargo.lock, pkgs/lighthouse/default.nix
* https://github.com/sigp/lighthouse/releases/tag/v5.1.1
* https://github.com/sigp/lighthouse/releases/tag/v5.1.2
=> lighthouse: 5.1.0 -> 5.1.2

pkgs/lighthouse/Cargo.lock, pkgs/lighthouse/default.nix
https://github.com/sigp/lighthouse/releases/tag/v5.1.3
=> lighthouse: 5.1.2 -> 5.1.3

pkgs/default.nix, pkgs/snarkjs/default.nix
This is related to Ethereum as it is a dependency of https://eth-store.w3eth.io 
I will package EthStorage later, using this as a dependency.
=> snarkjs: init at 0.7.3

pkgs/prysm/default.nix
https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.3
=> prysm: 5.0.2 -> 5.0.3

pkgs/nimbus/default.nix
Builds with `nix build '.#nimbus'`
=> nimbus: 24.2.2 -> 24.3.0

pkgs/besu/default.nix
=> besu: 24.1.2 -> 24.3.3

modules/mev-boost/default.nix
- **mev-boost: add holesky support**
=> mev boost holesky

pkgs/nimbus/default.nix
Builds with `nix build .#nimbus`
=> nimbus: 24.5.1 -> 24.6.0

pkgs/besu/default.nix, pkgs/default.nix
=> Update besu to 24.6.0

pkgs/rocketpool/default.nix
Seems to run as expected. I have not run the complete docker setup with this build.
=> rocketpool: 1.12.1 -> 1.13.7

pkgs/vouch/default.nix
=> vouch: 1.8.1 -> 1.9.0

pkgs/besu/default.nix
Update the besu package to 24.10.0
It's working for me... definitely read the release notes first though
=> besu: 24.6.0 -> 24.10.0

docs/apps.md, pkgs/default.nix
We build blsync so might as well make it official
=> geth: expose blsync

.envrc, flake.lock, flake.nix, lib.nix, mkdocs.nix, modules/testing.nix, pkgs/default.nix
The following changes have been implemented on this PR:
- **feat: update .envrc: nix-direnv version to `3.0.3` and remove deprecated `watch_nix_file`**
- **feat: remove devour-flake input**
- **feat: remove lib-extras input**
=> feat: misc updates

flake.lock, modules/prysm-beacon/args.nix, modules/prysm-validator/args.nix, modules/prysm-validator/default.test.nix, pkgs/by-name/re/reth/default.nix
This version is required for Pectra (on Ethereum Mainnet on May 7th)
=> reth 1.2.0 -> 1.3.12

pkgs/by-name/er/erigon/default.nix
https://github.com/erigontech/erigon/releases/tag/v3.0.4
=> erigon: 3.0.3 -> 3.0.4

pkgs/by-name/ro/rotki-bin/default.nix
Tested empirically to work OK.
=> rotki-bin: 1.37.1 -> 1.39.0

pkgs/by-name/ge/geth/default.nix
Bump Geth to latest stable version.
=> Update geth 1.15.11 -> 1.16.1

modules/geth/args.nix
Add the new hoodi testnet to Geth.
=> Add hoodi network to geth NixOS module.

pkgs/by-name/li/lighthouse/default.nix
=> lighthouse: 7.0.1 -> 7.1.0

pkgs/by-name/te/teku/default.nix
Update Teku to 25.7.1
Also hopefully this will get Buildbot unstuck... (edit: it did not)
=> Teku 24.2.0 -> 25.7.1

pkgs/by-name/er/erigon/default.nix
=> erigon: v3.0.4 -> v3.0.15

docs/apps.md
Some apps listed in the table do not match what's in the flake
Depends on #590
=> fix: apps discrepancies in docs

pkgs/by-name/bl/blutgang/default.nix, pkgs/by-name/et/ethdo/default.nix
=> chore(ethdo): update ethdo v1.35.2 -> v1.38.0

.github/workflows/update-readme.yaml, .mergify.yml
- **feat: update update-readme workflow**
- **feat: update mergify.yaml config**
=> readme workflows update
